### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by tara-matthew** [devnullone/didobin#22]
<img width="351" alt="Screenshot 2022-10-05 at 12 44 48" src="https://user-images.githubusercontent.com/24946946/194052881-0888fbbb-02e5-47a9-a6b7-772cb57c6de4.png">

Change text to 'Features'

**Comment by shubhamrawat090** [comment]
hi @taramatt93 is anyone working it? please assign it to me if not

**Comment by taramatt93** [comment]
Oh, I'm requesting to be assigned this :)

**Comment by shubhamrawat090** [comment]
okay no problem :)
