### ISSUE TITLE
Create a cookie banner

### ISSUE THREAD

**Issue by devnullone** [devnullone/didobin#5]
Add a cookie banner on the website

**Comment by shubhamrawat090** [comment]
Hi @devnullone, this looks interesting can you please assign this issue to me?

**Comment by devnullone** [comment]
> Hi @devnullone, this looks interesting can you please assign this issue to me?

Happy coding @shubhamrawat090 :)

**Comment by shubhamrawat090** [comment]
hey @devnullone thanks, I just had a doubt, do you want the cookie banner only on index.html or on other HTML pages too

**Comment by devnullone** [comment]
> hey @devnullone thanks, I just had a doubt, do you want the cookie banner only on index.html or on other HTML pages too

Add it to the index page

**Comment by shubhamrawat090** [comment]
okay thanks

**Comment by devnullone** [comment]
Hi @shubhamrawat090, your PR is approved!✅
Thanks :)
