### ISSUE TITLE
Improving SEO

### ISSUE THREAD

**Issue by roselam3** [devnullone/didobin#7]
I will :

- [x] Add missing meta description keywords,
- [x] Follow [ web.dev ](https://web.dev/measure/?url=https%3A%2F%2Fdidobin.pages.dev%2F) seo recommandations

**Comment by devnullone** [comment]
Good point!

**Comment by roselam3** [comment]
@devnullone It is done!

**Comment by devnullone** [comment]
Yes, I approve your PR! Thanks @roselam3
