### ISSUE TITLE
Can I add hover on menu? 

### ISSUE THREAD

**Issue by nishtha53** [devnullone/didobin#9]

**Comment by nishtha53** [comment]
Please assign this task to me

**Comment by devnullone** [comment]
> Please assign this task to me

Please go ahead!

**Comment by nishtha53** [comment]
Thankyou

**Comment by nishtha53** [comment]
@devnullone PR raised. Please check.

**Comment by devnullone** [comment]
> @devnullone PR raised. Please check.

Approved! ✅
